#1 Sprint 1
RomanAtreides/java-filmorate pull request #1
Opened 2022-07-08 23:06 UTC by RomanAtreides

2022-07-10 12:27 UTC, Fleaman777 requested changes

2022-07-10 21:49 UTC, RomanAtreides commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        }
Спасибо!

2022-07-10 21:50 UTC, RomanAtreides commented on src/main/java/ru/yandex/practicum/filmorate/exception/ValidationException.java
> +public class ValidationException extends RuntimeException {
Исправил. Не знал про этот класс, спасибо за подсказку.

2022-07-10 21:57 UTC, RomanAtreides commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final static Logger log = LoggerFactory.getLogger(FilmController.class);
Решил использовать аннотацию lombok

2022-07-10 21:57 UTC, RomanAtreides commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    }
Спасибо!

2022-07-10 21:59 UTC, RomanAtreides commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    void shouldThrowExceptionIfNameIsNullOrBlank() {
Спасибо!

2022-07-10 22:24 UTC, RomanAtreides commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +                "the eccentric scientist Doc Brown",
Исправил

2022-07-11 00:48 UTC, RomanAtreides commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public boolean validate(Film film) {
Подозреваю, что рано или поздно это придётся сделать, поэтому решил сделать сейчас

2022-07-11 00:51 UTC, RomanAtreides commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +    }
Решил всё-таки вынести валидацию в отдельный класс, соответственно и классы с тестами переделал

2022-07-11 14:25 UTC, merged