Add friends likes
RomanAtreides/java-filmorate pull request #2
Opened 2022-07-23 21:22 UTC by RomanAtreides

Sprint 9 project

2022-07-25 12:35 UTC, Fleaman777 requested changes

2022-07-25 12:35 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        userService.addFriend(user, friend);
хоть логика здесь простая и понятная, но лучше создать отдельный метод в сервисе, который бы сразу возвращал нужного юзера. 
т.к. контролл должен выполнять только ту логику, которая связана с получением реквестов и отправкой респонсов

2022-07-25 12:35 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        film.setId(++filmId);
более верная логика для такого метода была бы, просто возвращать новый айдишник, который дальше использовался бы в методе create, film.setId(generateFilmId())

2022-07-25 12:35 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        }
попробуй этот foreach переделать в stream, должно получится изящней)

2022-07-25 12:35 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    }
отличный получился стрим

2022-07-25 12:35 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserStorage.java
> +    Map<Long, User> getUsers();
не очень хороший метод для доступа к нашему стореджу, по сути, он означает дайте все то, что находится в хранилище, 
и с точки зрения скорости он не очень хорош, 
и с точки зрения безопасности

2022-07-26 19:33 UTC, RomanAtreides commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        film.setId(++filmId);
Согласен. Исправил

2022-07-26 20:01 UTC, RomanAtreides commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    }
Спасибо!

2022-07-29 18:47 UTC, RomanAtreides commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserStorage.java
> +    Map<Long, User> getUsers();
Удалил метод getUsers и исправил методы, в которых он используется

2022-07-29 20:14 UTC, RomanAtreides commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        userService.addFriend(user, friend);
Исправил.

2022-07-29 23:14 UTC, RomanAtreides commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        }
Исправил

2022-07-30 18:07 UTC, merged