Add database
RomanAtreides/java-filmorate pull request #3
Opened 2022-08-14 22:53 UTC by RomanAtreides

2022-08-15 21:31 UTC, Fleaman777 requested changes

2022-08-15 21:31 UTC, Fleaman777 commented on .gitignore
> +
в README надо расположить схему с тем какие у бд таблицы и как они связаны

2022-08-15 21:31 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/mapper/FilmMapper.java
> +                )
бест практис, больше чем 5 аргументов в конструктор не передавать, 
если нужно больше 5, то лучше использовать билдер

2022-08-15 21:31 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                throw new RuntimeException("Mpa is null!");
лучше использовтаь какое-нибудь специфическое исклчение или наше кастомное, что бы лучше понимтаь что пошло не так

2022-08-15 21:31 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    }
немного большой метод, попробуй повыделять из него части, которые можно было бы вынести в отдельные вспомогательные методы

2022-08-15 21:31 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                "LIMIT ?";
хорошие запросы, 
верхним регистром выделяешь ключевые слова например FROM, JOIN, GROUP , нижнем названия таблиц и полей 
это улучшает восприятие кода

2022-08-15 21:31 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +package ru.yandex.practicum.filmorate.storage;
попробуй в покедже сторедж, создать доп пекедж, напрмиер dbstorage и туда переместить классы которые связаны с дб

2022-08-15 21:31 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FriendshipStorage.java
> +public interface FriendshipStorage {
интересный подход с Friendship, такого еще не встречал) 
главное что работает

2022-08-15 21:31 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +}
тесты в целом неплохие, но согласно заданию, да правильней было бы 
для каждого сторедж класса, создать свой тест класс, в котором бы тестировались все публичные методы стореджа

а тест FilmoRateApplicationTests может быть пустым, т.к. ему нечего тестировать, т.к. его тестируемый класс FilmoRateApplication не содержит никакой логики

2022-08-15 21:31 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +		log.info("количество пользователей до добавления = " + usersCountBefore);
логи в тестах не нужны, т.к. ситуаций, когда они могут пригодится, не много :)
т.к. тесты либо проходят, либо нет, и чаще всего, когда они не проходят из вылетающих ошибок более-менее понятно, что пошло не так

2022-08-16 19:40 UTC, RomanAtreides commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                throw new RuntimeException("Mpa is null!");
Исправил

2022-08-16 19:41 UTC, RomanAtreides commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                "LIMIT ?";
Спасибо!

2022-08-16 19:49 UTC, RomanAtreides commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +		log.info("количество пользователей до добавления = " + usersCountBefore);
Исправил

2022-08-16 19:59 UTC, RomanAtreides commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +package ru.yandex.practicum.filmorate.storage;
Исправил

2022-08-18 03:53 UTC, RomanAtreides commented on src/main/java/ru/yandex/practicum/filmorate/storage/FriendshipStorage.java
> +public interface FriendshipStorage {
Тогда не буду трогать пока работает))

2022-08-18 03:54 UTC, RomanAtreides commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +}
Добавил тесты. Тест FilmoRateApplicationTests сделал пустым

2022-08-18 05:29 UTC, RomanAtreides commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    }
Разбил метод на 3 отдельных

2022-08-18 07:17 UTC, RomanAtreides commented on src/main/java/ru/yandex/practicum/filmorate/mapper/FilmMapper.java
> +                )
Исправил

2022-08-18 08:10 UTC, RomanAtreides commented on .gitignore
> +
Добавил

2022-08-18 19:19 UTC, Fleaman777 approved these changes

2022-08-18 19:19 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/storage/dbstorage/FilmDbStorageTests.java
> +    }
для начала, тесты неплохие, 
но тестовые методы лучше делать так, что бы в них проверялась какая-та 1 обособленная часть: добавление, удаление, изменение и т.д.

так в тестах будет чуть проще ориентироваться и через них будет проще понять поведение основной логики

можешь их не исправлять, это так, на будущее)

2022-08-18 19:19 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/storage/dbstorage/UserDbStorageTests.java
> +    public void shouldFindUserById() {
если в названии тест метода используется should, то хорошо бы указывать при каких условиях будет выполнено, то что идет после should 

например, 
shouldThrowNotUserExceptionWhenUserIdIsNotExist

это тоже можешь не исправлять, информация на будущее)

2022-08-19 16:38 UTC, RomanAtreides commented on src/test/java/ru/yandex/practicum/filmorate/service/FilmServiceTests.java
> +class FilmServiceTests {
Принято

2022-08-19 16:39 UTC, RomanAtreides commented on src/test/java/ru/yandex/practicum/filmorate/storage/dbstorage/FilmDbStorageTests.java
> +    }
Хорошо. Спасибо!

2022-08-19 16:40 UTC, RomanAtreides commented on src/test/java/ru/yandex/practicum/filmorate/storage/dbstorage/UserDbStorageTests.java
> +    public void shouldFindUserById() {
Спасибо за подсказку

2022-08-19 16:40 UTC, merged